name: rpc_generator
description: A generator used to generate RPC APIs.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

resolution: workspace

dependencies:
  rpc_annotations:
    git:
      url: https://github.com/steeple-org/flutter_rpc_generator.git
      path: rpc_annotations

  analyzer: ^7.7.1
  build: ^3.1.0
  code_builder: ^4.11.0
  collection: ^1.19.1
  dart_style: ^3.1.1
  source_gen: ^4.0.0
  meta: ^1.17.0

dev_dependencies:
  generator_test: ^0.6.0
  retrofit_generator: ^10.0.5
  test: ^1.26.3
