name: rpc_generator
description: A generator used to generate RPC APIs.
version: 1.1.0
publish_to: none

environment:
  sdk: ">=3.9.2 <4.0.0"

resolution: workspace

dependencies:
  rpc_annotations:
    git:
      url: https://github.com/steeple-org/flutter_rpc_generator.git
      path: rpc_annotations

  analyzer: ^8.2.0
  build: ^4.0.0
  code_builder: ^4.11.0
  collection: ^1.19.1
  dart_style: ^3.1.2
  source_gen: ^4.0.1
  meta: ^1.17.0

dev_dependencies:
  generator_test: ^0.6.0
  retrofit_generator:
    git:
      url: https://github.com/trevorwang/retrofit.dart.git
      path: generator
      # Contains our fix for nullable entities in CallAdapter.
      ref: 63545c210ad39fa1c58668222ad1a0d2cd461355
  # Currently tests do not work because of this issue: https://github.com/dart-lang/test/issues/2535
  test: ^1.26.3
