name: rpc_annotations
description: A package containing annotations for generating RPC APIs.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

resolution: workspace

dependencies:
  meta: ^1.15.0
