name: rpc_annotations
description: A package containing annotations for generating RPC APIs.
version: 1.1.0
publish_to: none

environment:
  sdk: ">=3.9.2 <4.0.0"

resolution: workspace

dependencies:
  meta: ^1.17.0
