name: rpc_annotations
description: A package containing annotations for generating RPC APIs.
version: 1.1.1
publish_to: none

environment:
  sdk: ">=3.9.2 <4.0.0"

resolution: workspace

dependencies:
  # Be careful, the version of this package must not be higher than the one pinned by the Flutter SDK.
  # Check here: https://github.com/flutter/flutter/blob/stable/packages/flutter/pubspec.yaml
  meta: ^1.16.0
